CREATE TABLE IF NOT EXISTS bookings (
    id SERIAL PRIMARY KEY,
    user_id INT REFERENCES users(id) ON DELETE SET NULL,
    show_id INT REFERENCES shows(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'booked',
    total_amount INT NUT NULL,
    booked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);